### ISSUE TITLE
Player skulls no longer working in 1.20.2

### ISSUE THREAD

**Issue by Leomelonseeds** [promcteam/BossShopPro#43]
Hello, after updating my server to the latest Paper 1.20.2-234, trying to open any menu with a custom player skull will give an error.

The error:
```
org.bukkit.command.CommandException: Unhandled exception executing command 'bossshop' in plugin BossShopPro v2.1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.20.2.jar:git-Paper-234]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.leomelonseeds.missilewars.listener.CustomItemListener.useItem(CustomItemListener.java:197) ~[missilewars-0.7.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor605.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-234]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-234]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-234]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593) ~[paper-1.20.2.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[paper-1.20.2.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.20.2.jar:git-Paper-234]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:540) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1965) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-234]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
        at org.black_ixx.bossshop.managers.item.ItemDataPartCustomSkull.readSkullTexture(ItemDataPartCustomSkull.java:80) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.item.ItemStackTranslator.transformCustomSkull(ItemStackTranslator.java:80) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.item.ItemStackTranslator.translateItemStack(ItemStackTranslator.java:69) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.ShopCustomizer.addItem(ShopCustomizer.java:186) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:136) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.ShopCustomizer.createInventory(ShopCustomizer.java:41) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.core.BSShop.createInventory(BSShop.java:196) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.core.BSShop.openInventory(BSShop.java:289) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.core.BSShops.openShop(BSShops.java:128) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.core.BSShops.openShop(BSShops.java:102) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.CommandManager.playerCommandOpenShop(CommandManager.java:217) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:167) ~[bossshoppro-2.1.0-20230422.101939-23.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

```

The broken item:
```
CharacterInformation:
    MenuItem:
    - type:PLAYER_HEAD
    - amount:1
    - durability:3
    - playerhead:%player%
    - 'lore:'
    - 'lore:&bServer TPS: &f%server_tps_1%'
    - 'lore:&bPing: &f%player_ping%'
```

Thank you in advance for helping.

**Comment by Latch93** [comment]
Same issue after 1.20.2 Paper update. tnt_block object is fine, skulls are not
`tnt_block:
    MenuItem:
    - '%rewarditem_1%'
    - lore:&8Click to get it for &c%price%&e.
    RewardType: ITEM
    PriceType: money
    Price: 1000
    Reward:
    - - type:quartz_block
      - amount:64
    Message: '&eYou bought %itemname%!'
    ExtraPermission: '' 
    InventoryLocation: 7
  king_steve_head2:
    RewardType: ITEM
    Reward: 
    - - type:PLAYER_HEAD
      - customskull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjFjNmEwMTNiZjczYWZjMDBlYjFmODdhNTkxYTI1NmQyMGQzZjc1YWE4ZTlkY2JmMDhhYjZkNjY1ZmM0NjUxNiJ9fX0=
      - name:&f&bLaughing Man Head
      - 'lore1:LTS - Sep 15th 2023'
      - 'lore2:Worth - $2500'
    PriceType: money
    Price: 2500
    MenuItem:
    - '%rewarditem_1%'
    - lore:&8Click to get it for &c%price%&e.
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 8
  technoblade:
    RewardType: ITEM
    Reward: 
    - - type:PLAYER_HEAD
      - customskull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGYxZmI3ZDM0MjUxM2M5MmVjZTU0YmZkMDE2ZjEwZTFhZDg4NzRlY2YzYzhkNDdhMTFjN2FhYzMzODk1Y2JlZiJ9fX0=
      - name:&6&lThanos Head
      - 'lore1:LTS - Sep 15th 2023'
      - 'lore2:Worth - $2500'
    PriceType: money
    MenuItem:
    - '%rewarditem_1%'
    - lore:&8Click to get it for &c%price%&e.
    Price: 2500
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 9`
