### ISSUE TITLE
custom skull error in 1.20.2

### ISSUE THREAD

**Issue by mcdoeswhat** [promcteam/BossShopPro#46]
```
[21:04:36 WARN]: java.lang.NullPointerException: Profile name must not be null
[21:04:36 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:235)
[21:04:36 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemDataPartCustomSkull.transformSkull(ItemDataPartCustomSkull.java:42)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemDataPartCustomSkull.transform(ItemDataPartCustomSkull.java:99)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemDataPart.transformItem(ItemDataPart.java:222)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemDataPart.transformItem(ItemDataPart.java:140)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemDataPart.transformItem(ItemDataPart.java:118)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemStackCreator.createItemStack(ItemStackCreator.java:96)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.item.ItemStackCreator.createItemStack(ItemStackCreator.java:57)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.BuyItemHandler.createBuyItem(BuyItemHandler.java:197)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.BuyItemHandler.loadItem(BuyItemHandler.java:47)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.config.BSConfigShop.loadItems(BSConfigShop.java:184)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.config.BSConfigShop.setup(BSConfigShop.java:96)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.config.BSConfigShop.<init>(BSConfigShop.java:72)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.config.BSConfigShop.<init>(BSConfigShop.java:42)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.config.BSConfigShop.<init>(BSConfigShop.java:38)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.core.BSShops.loadShop(BSShops.java:80)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.core.BSShops.loadShops(BSShops.java:53)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.core.BSShops.<init>(BSShops.java:31)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.managers.ClassManager.setupDependentClasses(ClassManager.java:136)
[21:04:36 WARN]:        at bossshoppro-2.1.0-20230422.101939-23.jar//org.black_ixx.bossshop.BossShop$1.run(BossShop.java:81)
[21:04:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[21:04:36 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:04:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:04:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:04:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:04:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:04:36 ERROR]: [BossShopPro] Probably caused by Config Mistakes.
[21:04:36 ERROR]: [BossShopPro] For more help please send me a PM at Spigot.
```

Skulls not showing in menu

server: git-Purpur-2092 (MC: 1.20.2)*

**Comment by Travja** [comment]
This should be resolved with the latest dev build on Discord.
